public class calculator {

    public double firstnumber;
    public double secondnumber;
    public void multiply(){
        system.debug(firstnumber*secondnumber);
    }
     public void devide(){
        system.debug(firstnumber/secondnumber);
    }
    public void subtract(){
        system.debug(firstnumber-secondnumber);
    }
    
    public void add(){
        system.debug(firstnumber+secondnumber);
    }
    
    
}