public  class  employee1 {
    public string Department,Location,Name,Designation;
    public Integer empId,Salary;
    Public employee1(Integer EmpId,String Name,String Department,string Designation,Integer Salary,String Location)
    {
        this.Name=Name;
        this.Designation=Designation;
        this.Department=Department;
        this.Location=Location;
        this.empId=empId;
        this.salary=salary;
    }
        

}